@MailTmAPI_HostAddress = https://localhost:60957

GET {{MailTmAPI_HostAddress}}/weatherforecast/
Accept: application/json


###


GET {{MailTmAPI_HostAddress}}/mailtm/
Accept: application/json


###

POST {{MailTmAPI_HostAddress}}/mailtm/
Accept: application/json



###

GET {{MailTmAPI_HostAddress}}/domains/
Accept: application/json


###

POST {{MailTmAPI_HostAddress}}/accounts/
Accept: application/json
Content-Type: application/json


###
